# Generated by Django 5.0.1 on 2026-02-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_migrate_tags_to_tasktag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags_old',
        ),
    ]
